name: Keep Awake

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:
  
jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Print Time
        run: date -u

      - name: Ping Streamlit
        run: |
          curl -I https://review-system-krc.streamlit.app
