name: Keep Awake

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s -o /dev/null -w "%{http_code}" https://review-system-krc.streamlit.app || true
