name: Keep Awake

on:
  schedule:
    - cron: '0 */1 * * *'  # 1시간마다 실행

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -L https://review-system-krc.streamlit.app
